/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRefreshStockSnapshotsRouteImport } from './routes/api/public/hooks/refresh-stock-snapshots'
import { Route as ApiPublicHooksRefreshIndexConstituentsRouteImport } from './routes/api/public/hooks/refresh-index-constituents'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshStockSnapshotsRoute =
  ApiPublicHooksRefreshStockSnapshotsRouteImport.update({
    id: '/api/public/hooks/refresh-stock-snapshots',
    path: '/api/public/hooks/refresh-stock-snapshots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshIndexConstituentsRoute =
  ApiPublicHooksRefreshIndexConstituentsRouteImport.update({
    id: '/api/public/hooks/refresh-index-constituents',
    path: '/api/public/hooks/refresh-index-constituents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/methodology': typeof MethodologyRoute
  '/results': typeof ResultsRoute
  '/api/public/hooks/refresh-index-constituents': typeof ApiPublicHooksRefreshIndexConstituentsRoute
  '/api/public/hooks/refresh-stock-snapshots': typeof ApiPublicHooksRefreshStockSnapshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/methodology': typeof MethodologyRoute
  '/results': typeof ResultsRoute
  '/api/public/hooks/refresh-index-constituents': typeof ApiPublicHooksRefreshIndexConstituentsRoute
  '/api/public/hooks/refresh-stock-snapshots': typeof ApiPublicHooksRefreshStockSnapshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/methodology': typeof MethodologyRoute
  '/results': typeof ResultsRoute
  '/api/public/hooks/refresh-index-constituents': typeof ApiPublicHooksRefreshIndexConstituentsRoute
  '/api/public/hooks/refresh-stock-snapshots': typeof ApiPublicHooksRefreshStockSnapshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/methodology'
    | '/results'
    | '/api/public/hooks/refresh-index-constituents'
    | '/api/public/hooks/refresh-stock-snapshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/methodology'
    | '/results'
    | '/api/public/hooks/refresh-index-constituents'
    | '/api/public/hooks/refresh-stock-snapshots'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/methodology'
    | '/results'
    | '/api/public/hooks/refresh-index-constituents'
    | '/api/public/hooks/refresh-stock-snapshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  MethodologyRoute: typeof MethodologyRoute
  ResultsRoute: typeof ResultsRoute
  ApiPublicHooksRefreshIndexConstituentsRoute: typeof ApiPublicHooksRefreshIndexConstituentsRoute
  ApiPublicHooksRefreshStockSnapshotsRoute: typeof ApiPublicHooksRefreshStockSnapshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-stock-snapshots': {
      id: '/api/public/hooks/refresh-stock-snapshots'
      path: '/api/public/hooks/refresh-stock-snapshots'
      fullPath: '/api/public/hooks/refresh-stock-snapshots'
      preLoaderRoute: typeof ApiPublicHooksRefreshStockSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-index-constituents': {
      id: '/api/public/hooks/refresh-index-constituents'
      path: '/api/public/hooks/refresh-index-constituents'
      fullPath: '/api/public/hooks/refresh-index-constituents'
      preLoaderRoute: typeof ApiPublicHooksRefreshIndexConstituentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  MethodologyRoute: MethodologyRoute,
  ResultsRoute: ResultsRoute,
  ApiPublicHooksRefreshIndexConstituentsRoute:
    ApiPublicHooksRefreshIndexConstituentsRoute,
  ApiPublicHooksRefreshStockSnapshotsRoute:
    ApiPublicHooksRefreshStockSnapshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
